package com.cracknellj.fare.offline.tfl;

import com.cracknellj.fare.io.StationFileReader;
import com.cracknellj.fare.io.StationFileWriter;
import com.cracknellj.fare.objects.Station;
import org.junit.Test;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

//Station{stationId='940GZZLUBNK', stationName='Bank'}ZBA ---- [ZMM, MON, 940GZZLUBNK, EC4R9AA] ???
//https://techforum.tfl.gov.uk/t/tube-stations-with-crs-and-nlc-codes/612/3
public class AddCrsCodesToTflStations {

    @Test
    public void test() throws Exception {
        Map<String, Station> stationsAsMap = StationFileReader.getStationsAsMap();
        list.forEach(s -> {
            Station station = stationsAsMap.get(s[2]);
            if (station != null) {
                if (station.crs == null) {
                    station.crs = s[0];
                } else {
                    System.out.println(station + station.crs + " ---- " + Arrays.toString(s));
                }
            }
        });
        StationFileWriter.writeStations(new ArrayList<>(stationsAsMap.values()));
    }

    @Test
    public void showMissingCrsCodes() throws Exception {
        List<Station> collect = StationFileReader.getStations().stream().filter(s -> s.crs == null).collect(Collectors.toList());
        System.out.println(collect);
    }

    List<String[]> list = Arrays.asList(
            new String[] {"NGR","NGW","940GZZLUNGW","SE100PH"},
            new String[] {"QPW","QPK","910GQPRK","NW66NN"},
            new String[] {"SDS","SFS","940GZZLUSFS","SW196LL"},
            new String[] {"SRA","SFD","910GSTFD","E151DE"},
            new String[] {"WMP","WMP","940GZZLUWIP","SW197HR"},
            new String[] {"ZAD","ALD","940GZZLUALD","EC3N1AH"},
            new String[] {"ZAE","ALE","940GZZLUADE","E17PT"},
            new String[] {"ZAG","AGR","940GZZLUASG","N111AN"},
            new String[] {"ZAL","ARL","940GZZLUASL","N51LP"},
            new String[] {"ZAN","ANG","940GZZLUAGL","EC1V1NE"},
            new String[] {"ZAP","ALP","940GZZLUALP","HA04LL"},
            new String[] {"ZAR","ARC","940GZZLUACY","N195RQ"},
            new String[] {"ZAS","ZAS","940GZZDLALL","E146NT"},
            new String[] {"ZAT","ACT","940GZZLUACT","W38HN"},
            new String[] {"ZBA","BNK","940GZZLUBNK","EC3V3LA"},
            new String[] {"ZBC","ZBC","940GZZDLBOW","E33EF"},
            new String[] {"ZBD","BDS","940GZZLUBND","W1R1FE"},
            new String[] {"ZBE","BER","940GZZLUBMY","SE164RX"},
            new String[] {"ZBG","BGR","910GBOWESPK","N112EU"},
            new String[] {"ZBH","ZBW","940GZZDLBLA","E149QE"},
            new String[] {"ZBI","BHL","940GZZLUBKH","IG95ET"},
            new String[] {"ZBJ","ZBP","940GZZDLBPK","E65PF"},
            new String[] {"ZBM","BOS","940GZZLUBOS","TW89LQ"},
            new String[] {"ZBN","BDE","940GZZLUBKE","IG61NB"},
            new String[] {"ZBO","BUR","940GZZLUBTK","HA80LA"},
            new String[] {"ZBP","BPK","940GZZLUBZP","NW32AL"},
            new String[] {"ZBQ","BCT","940GZZLUBSC","W149AX"},
            new String[] {"ZBR","BWR","940GZZLUBWR","E34DH"},
            new String[] {"ZBS","BST","940GZZLUBST","NW15LL"},
            new String[] {"ZBT","BTX","940GZZLUBTX","NW119UA"},
            new String[] {"ZBU","BOR","940GZZLUBOR","SE11JX"},
            new String[] {"ZBV","ZBT","940GZZDLBEC","E65NT"},
            new String[] {"ZBW","BBB","940GZZLUBBB","E33NF"},
            new String[] {"ZBY","ZBW","940GZZLUBWT","W24QH"},
            new String[] {"ZBZ","BEC","940GZZLUBEC","RM94TP"},
            new String[] {"ZCA","CPS","940GZZLUCPS","SW129DU"},
            new String[] {"ZCB","CNT","940GZZLUCGT","E161DQ"},
            new String[] {"ZCC","CPC","940GZZLUCPC","SW47AJ"},
            new String[] {"ZCD","COL","940GZZLUCND","NW95HR"},
            new String[] {"ZCE","ZCH","940GZZDLCUS","E163AT"},
            new String[] {"ZCF","CHF","940GZZLUCFM","NW32BP"},
            new String[] {"ZCG","CHG","940GZZLUCWL","IG76NT"},
            new String[] {"ZCH","ZXH","940GZZDLCLA","E149RE"},
            new String[] {"ZCI","CHP","940GZZLUCWP","W45NE"},
            new String[] {"ZCK","CFS","940GZZLUCKS","EN40DZ"},
            new String[] {"ZCL","CLW","940GZZLUCSD","SW192HR"},
            new String[] {"ZCM","ZCM","940GZZLUCSM","HP51DH"},
            new String[] {"ZCN","CPN","910GCLPHHS","SW47TS"},
            new String[] {"ZCO","CRX","940GZZLUCXY","WD33DY"},
            new String[] {"ZCP","CPK","940GZZLUCPK","HA86RN"},
            new String[] {"ZCQ","ZCY","940GZZDLCYP","E65NA"},
            new String[] {"ZCR","CRD","940GZZLUCAR","N79BA"},
            new String[] {"ZCS","ZCS","940GZZDLCUT","SE109DW"},
            new String[] {"ZCT","CTN","940GZZLUCTN","NW18NH"},
            new String[] {"ZCV","COV","940GZZLUCGN","WC2E9JT"},
            new String[] {"ZCY","CYL","940GZZLUCHL","WC1V6DR"},
            new String[] {"ZCZ","CWF","940GZZLUCYF","E144HJ"},
            new String[] {"ZDB","DEB","940GZZLUDBN","IG103TG"},
            new String[] {"ZDE","DGE","940GZZLUDGE","RM108AA"},
            new String[] {"ZDH","DGH","940GZZLUDGY","RM95AN"},
            new String[] {"ZDO","DHL","940GZZLUDOH","NW105NB"},
            new String[] {"ZDP","ZDP","940GZZDLDEP","SE84HH"},
            new String[] {"ZDR","ZDR","940GZZDLDEV","E34DP"},
            new String[] {"ZEA","EAC","940GZZLUEAN","W120BP"},
            new String[] {"ZEB","ERB","940GZZLUERB","W21EB"},
            new String[] {"ZEC","ECM","940GZZLUECM","W53LD"},
            new String[] {"ZED","EDG","940GZZLUEGW","HA87AW"},
            new String[] {"ZEE","ETE","940GZZLUEAE","HA51QZ"},
            new String[] {"ZEF","EFY","940GZZLUEFY","N20NW"},
            new String[] {"ZEG","EPP","940GZZLUEPG","CM164HW"},
            new String[] {"ZEH","EHM","940GZZLUEHM","E62JA"},
            new String[] {"ZEI","ZEI","940GZZDLEIN","E149GF"},
            new String[] {"ZEK","EMB","910GCHRX","WC2N6NS"},
            new String[] {"ZEM","ERD","940GZZLUERC","NW15DD"},
            new String[] {"ZEP","EPK","940GZZLUEPK","RM124RW"},
            new String[] {"ZER","ZER","940GZZDLELV","SE137RN"},
            new String[] {"ZES","ESQ","940GZZLUESQ","NW12BN"},
            new String[] {"ZET","ECT","940GZZLUECT","SW59QA"},
            new String[] {"ZFA","FLP","940GZZLUFLP","IG63HD"},
            new String[] {"ZFB","FBY","940GZZLUFBY","SW61BY"},
            new String[] {"ZFC","FYC","940GZZLUFYC","N32RY"},
            new String[] {"ZFR","FRD","940GZZLUFYR","NW36OP"},
            new String[] {"ZGA","GHL","940GZZLUGTH","IG26UD"},
            new String[] {"ZGC","ZGH","940GZZDLGAL","E66FS"},
            new String[] {"ZGE","GPK","940GZZLUGPK","W1V9HG"},
            new String[] {"ZGG","GGR","940GZZLUGGN","NW117RN"},
            new String[] {"ZGH","GRH","940GZZLUGGH","IG75QB"},
            new String[] {"ZGP","GPS","940GZZLUGPS","NW14LH"},
            new String[] {"ZGR","GRD","940GZZLUGTR","SW74SF"},
            new String[] {"ZGS","GST","940GZZLUGDG","W1P9PA"},
            new String[] {"ZGW","ZGR","940GZZLUGHK","W128EG"},
            new String[] {"ZHA","HMD","940GZZLUHSC","W67DP"},
            new String[] {"ZHB","HBT","940GZZLUHBT","EN55RP"},
            new String[] {"ZHC","HNC","940GZZLUHWC","TW31JG"},
            new String[] {"ZHD","HDN","940GZZLUHGD","UB109NR"},
            new String[] {"ZHE","HNE","940GZZLUHWE","TW34AB"},
            new String[] {"ZHG","HIG","940GZZLUHGT","N65FJ"},
            new String[] {"ZHL","HLN","940GZZLUHGR","W51DL"},
            new String[] {"ZHM","HMP","940GZZLUHTD","NW31QG"},
            new String[] {"ZHN","HND","940GZZLUHCL","NW43AS"},
            new String[] {"ZHO","HOL","940GZZLUHBN","WC2B6AA"},
            new String[] {"ZHP","HPK","940GZZLUHPK","W113RB"},
            new String[] {"ZHQ","ZHQ","940GZZDLHEQ","E144JH"},
            new String[] {"ZHR","HRD","940GZZLUHWY","N78HS"},
            new String[] {"ZHT","HAI","940GZZLUHLT","IG63BD"},
            new String[] {"ZHU","HCH","940GZZLUHCH","RM126LS"},
            new String[] {"ZHW","HNW","940GZZLUHWT","TW33DH"},
            new String[] {"ZHX","HTX","940GZZLUHNX","TW62JL"},
            new String[] {"ZHY","HPC","940GZZLUHPC","SW1X7LY"},
            new String[] {"ZHZ","HMS","940GZZLUHSD","W67SY"},
            new String[] {"ZIC","ICK","940GZZLUICK","UB108PD"},
            new String[] {"ZIG","ZIG","940GZZDLISL","E143GR"},
            new String[] {"ZIQ","ZWI","940GZZDLCAN","E144EG"},
            new String[] {"ZKE","KEN","940GZZLUKNG","SE114QJ"},
            new String[] {"ZKI","KIL","910GBRBY","NW67QL"},
            new String[] {"ZKN","KNB","940GZZLUKNB","SW1X7LJ"},
            new String[] {"ZKP","KPK","910GKLBRNHR","NW65AD"},
            new String[] {"ZKY","KBY","940GZZLUKBY","NW99EG"},
            new String[] {"ZLA","LAN","940GZZLULGT","W23PF"},
            new String[] {"ZLC","LSQ","940GZZLULSQ","WC2H0AP"},
            new String[] {"ZLE","LYS","940GZZLULYS","E111HE"},
            new String[] {"ZLG","ZLG","940GZZLULAD","W106HJ"},
            new String[] {"ZLN","LAM","940GZZLULBN","SE17XG"},
            new String[] {"ZLO","LTN","940GZZLULGN","IG104PD"},
            new String[] {"ZLR","ZLR","940GZZLULRD","W106SZ"},
            new String[] {"ZLY","LEY","940GZZLULYN","E105PS"},
            new String[] {"ZMA","MAR","940GZZLUMBA","W1R1DD"},
            new String[] {"ZMC","ZMC","940GZZDLMUD","E149UW"},
            new String[] {"ZME","MLE","940GZZLUMED","E34DH"},
            new String[] {"ZMH","MAN","940GZZLUMSH","EC4N6JD"},
            new String[] {"ZML","MHE","940GZZLUMHL","NW71BS"},
            new String[] {"ZMM","MON","940GZZLUBNK","EC4R9AA"},
            new String[] {"ZMN","MCR","940GZZLUMTC","NW12JA"},
            new String[] {"ZMO","MOR","940GZZLUMDN","SM45AZ"},
            new String[] {"ZMP","MPK","940GZZLUMPK","HA62JQ"},
            new String[] {"ZMR","MNR","940GZZLUMRH","N41BZ"},
            new String[] {"ZMV","MDV","940GZZLUMVL","W91JS"},
            new String[] {"ZNA","NAC","940GZZLUNAN","W36UP"},
            new String[] {"ZND","NWD","940GZZLUNOW","HA62XL"},
            new String[] {"ZNE","NEL","940GZZLUNEN","W53AF"},
            new String[] {"ZNF","NFD","940GZZLUNFD","W139QU"},
            new String[] {"ZNG","NHG","940GZZLUNHG","W113HT"},
            new String[] {"ZNH","NHR","940GZZLUNHA","HA27SR"},
            new String[] {"ZNK","NWP","940GZZLUNKP","HA30AT"},
            new String[] {"ZNN","NEA","940GZZLUNDN","NW101PH"},
            new String[] {"ZNO","NHT","940GZZLUNHT","UB54AA"},
            new String[] {"ZNP","NEP","910GILFENBP","IG27RN"},
            new String[] {"ZNS","NWH","940GZZLUNWH","HA61NZ"},
            new String[] {"ZOA","OAK","940GZZLUOAK","N144UT"},
            new String[] {"ZOC","OXC","940GZZLUOXC","W1R1AB"},
            new String[] {"ZOV","OVL","940GZZLUOVL","SE114PP"},
            new String[] {"ZOY","OST","940GZZLUOSY","TW74PU"},
            new String[] {"ZPB","PUT","940GZZLUPYB","SW63UH"},
            new String[] {"ZPC","PIC","940GZZLUPCC","W1V9LB"},
            new String[] {"ZPD","ZRP","940GZZDLPRE","E161SL"},
            new String[] {"ZPE","PER","940GZZLUPVL","UB67PG"},
            new String[] {"ZPG","PGR","940GZZLUPSG","SW64HJ"},
            new String[] {"ZPI","PIN","940GZZLUPNR","HA55LZ"},
            new String[] {"ZPK","PRY","940GZZLUPKR","W53EL"},
            new String[] {"ZPL","ZPO","940GZZDLPOP","E140BX"},
            new String[] {"ZPM","ZPM","940GZZDLPUD","E152PJ"},
            new String[] {"ZPO","PIM","940GZZLUPCO","SW1V2JA"},
            new String[] {"ZPR","ZPT","940GZZLUPRD","HA30PS"},
            new String[] {"ZPS","PLW","940GZZLUPLW","E130JU"},
            new String[] {"ZPU","EPY","940GZZLUEPY","SW152SP"},
            new String[] {"ZQB","QBY","940GZZLUQBY","HA85NP"},
            new String[] {"ZQS","SWF","940GZZLUSWF","E181JJ"},
            new String[] {"ZQW","QWY","940GZZLUQWY","W24SS"},
            new String[] {"ZRA","RCP","940GZZLURVP","W60UG"},
            new String[] {"ZRB","ZRV","940GZZDLRVC","E161LE"},
            new String[] {"ZRC","ZRA","940GZZDLRAL","E162QD"},
            new String[] {"ZRG","RUG","940GZZLURSG","HA46NF"},
            new String[] {"ZRL","RLN","940GZZLURYL","HA55EJ"},
            new String[] {"ZRM","RUM","940GZZLURSM","HA49AA"},
            new String[] {"ZRP","RPK","940GZZLURGP","NW15HA"},
            new String[] {"ZRS","RSQ","940GZZLURSQ","WC1N1LG"},
            new String[] {"ZRU","RUI","940GZZLURSP","HA48LD"},
            new String[] {"ZRV","ROD","940GZZLURVY","IG96LN"},
            new String[] {"ZRY","ZRO","940GZZLURYO","W26ET"},
            new String[] {"ZSA","SGT","940GZZLUSGT","N146JT"},
            new String[] {"ZSC","SWC","940GZZLUSWC","NW36HY"},
            new String[] {"ZSE","SEL","940GZZLUSEA","W54QB"},
            new String[] {"ZSF","STB","940GZZLUSFB","W60XS"},
            new String[] {"ZSG","STG","940GZZLUSGN","E14AQ"},
            new String[] {"ZSH","SHL","910GSDBRYHH","HA13RA"},
            new String[] {"ZSI","SWM","940GZZLUSWN","SW191DE"},
            new String[] {"ZSJ","SJW","940GZZLUSJW","NW89TY"},
            new String[] {"ZSK","SKN","940GZZLUSKS","SW72NB"},
            new String[] {"ZSL","STK","940GZZLUSKW","SW99AE"},
            new String[] {"ZSM","STA","940GZZLUSTM","HA74PD"},
            new String[] {"ZSN","SNB","940GZZLUSNB","E111QE"},
            new String[] {"ZSO","SSQ","940GZZLUSSQ","SW1W8BB"},
            new String[] {"ZSP","STP","940GZZLUSPU","EC1A7AJ"},
            new String[] {"ZSQ","ZSQ","940GZZDLSOQ","E149UJ"},
            new String[] {"ZSS","SJP","940GZZLUSJP","SW1H9AT"},
            new String[] {"ZSW","SWK","910GWLOE","SE18NW"},
            new String[] {"ZSX","SHR","940GZZLUSHH","HA28HN"},
            new String[] {"ZSY","STN","940GZZLUSUT","HA02LA"},
            new String[] {"ZTB","TBE","940GZZLUTBC","SW179AH"},
            new String[] {"ZTC","TCR","940GZZLUTCR","W1T1UQ"},
            new String[] {"ZTG","ZTG","940GZZDLTWG","EC3N2PU"},
            new String[] {"ZTH","THL","910GFENCHRS","EC3N4DJ"},
            new String[] {"ZTL","TPL","940GZZLUTPN","N153NX"},
            new String[] {"ZTM","TEM","940GZZLUTMP","WC2R2PH"},
            new String[] {"ZTO","TBY","940GZZLUTBY","SW170SU"},
            new String[] {"ZTP","TPK","940GZZLUTFP","N195QB"},
            new String[] {"ZTR","TGR","940GZZLUTNG","W41LR"},
            new String[] {"ZTW","TOT","940GZZLUTAW","N209QP"},
            new String[] {"ZTY","THB","940GZZLUTHB","CM167EU"},
            new String[] {"ZUB","UPB","940GZZLUUPB","RM126PL"},
            new String[] {"ZUP","UPK","940GZZLUUPK","E139AP"},
            new String[] {"ZUX","UXB","940GZZLUUXB","UB81JZ"},
            new String[] {"ZUY","UPY","940GZZLUUPY","IG119LS"},
            new String[] {"ZWC","WCT","940GZZLUWCY","W127RH"},
            new String[] {"ZWD","WGN","940GZZLUWOG","N224HH"},
            new String[] {"ZWE","WAC","940GZZLUWTA","W36UP"},
            new String[] {"ZWF","ZWF","940GZZDLWFE","E148JD"},
            new String[] {"ZWG","WLG","940GZZLUWIG","NW24QT"},
            new String[] {"ZWH","WFY","940GZZLUWFN","N31NT"},
            new String[] {"ZWI","WSP","940GZZLUWOP","N128SE"},
            new String[] {"ZWK","WKN","940GZZLUWKN","W149NL"},
            new String[] {"ZWM","WMS","940GZZLUWSM","SW1A2JR"},
            new String[] {"ZWN","WAN","940GZZLUWSD","E112NT"},
            new String[] {"ZWO","WFD","940GZZLUWOF","IG80HW"},
            new String[] {"ZWS","WST","940GZZLUWRR","NW13AA"},
            new String[] {"ZWT","WAT","940GZZLUWAF","WD17LE"},
            new String[] {"ZWU","ZWP","940GZZLUWSP","W111AB"},
            new String[] {"ZWV","WAR","940GZZLUWKA","W92PT"},
            new String[] {"ZWX","WHR","940GZZLUWHW","HA14HE"},
            new String[] {"ZWY","WPK","940GZZLUWYP","HA99AA"}
            );
}
